version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app/models:/app/app/models
    environment:
      - MODEL_DIR=/app/app/models
      - DEBUG=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/model"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped 